name: Deploy to AWS Fargate

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code - MUST be done before Docker build
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (assuming Node is needed for your build process)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Define Unique Image Tag based on commit SHA
      - name: Set image tag
        id: set_tag
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c 1-8)" >> $GITHUB_ENV

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 5: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Define ECR repository path and container name
      - name: Set ECR repository details
        id: ecr_details
        run: |
          echo "ECR_REPOSITORY=711538462588.dkr.ecr.us-east-1.amazonaws.com/myclinic-api" >> $GITHUB_ENV
          echo "CONTAINER_NAME=myclinic-app-container" >> $GITHUB_ENV # Ensure this matches your JSON!
          
      - name: Build, tag, and push image to ECR
        # This step assumes a file named 'Dockerfile' exists in the repository root (./)
        run: |
          docker build -t myclinic-api .
          docker tag myclinic-api:latest ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker tag myclinic-api:latest ${{ env.ECR_REPOSITORY }}:latest
          docker push ${{ env.ECR_REPOSITORY }}:latest


      # 2. Render Task Definition JSON with the new image tag
      - name: Fill in the new image in the Task Definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        id: render-container
        with:
          task-definition: task-definition.json 
          container-name: ${{ env.CONTAINER_NAME }} 
          image: ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} # Use the unique tag

      # 3. REGISTER and DEPLOY the service using the rendered JSON file
      - name: Register Task Definition and Deploy to ECS Fargate
        run: |
          # The render step outputs the path to the modified JSON file
          TASK_DEFINITION_FILE=${{ steps.render-container.outputs.task-definition }}
          
          # Register the new Task Definition with AWS and capture the ARN
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://$TASK_DEFINITION_FILE \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
            
          echo "Registered Task Definition ARN: $TASK_DEF_ARN"
          
          # Update the ECS service with the newly registered ARN
          aws ecs update-service \
            --cluster myclinic-cluster \
            --service myclincs-web-api-services \
            --task-definition $TASK_DEF_ARN \
            --force-new-deployment
