name: Deploy to AWS Fargate

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        run: |
          docker build -t myclinic-api .
          docker tag myclinic-api:latest 711538462588.dkr.ecr.us-east-1.amazonaws.com/myclinic-api:latest
          docker push 711538462588.dkr.ecr.us-east-1.amazonaws.com/myclinic-api:latest


      - name: Deploy to ECS Fargate
        run: |
          aws ecs update-service \
            --cluster myclinic-cluster \
            --service myclinic-api-service \
            --force-new-deployment
